---
create_user: camille
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']
domain: portfolio
repository: git@github.com:camfeghali/portfolio.git